"""business: projects verticals scales cups records

Revision ID: 5afa0ebb17fe
Revises: ddbd4fe1b249
Create Date: 2026-05-03 23:51:16.932416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5afa0ebb17fe'
down_revision: Union[str, Sequence[str], None] = 'ddbd4fe1b249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 启用 trigram 扩展（cups.cup_number 使用 gin_trgm_ops）
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cup_number', sa.String(length=32), nullable=False),
    sa.Column('current_tare_g', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('latest_calibration_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cups')),
    sa.UniqueConstraint('cup_number', name=op.f('uq_cups_cup_number'))
    )
    op.create_index('ix_cups_number_trgm', 'cups', ['cup_number'], unique=False, postgresql_using='gin', postgresql_ops={'cup_number': 'gin_trgm_ops'})
    op.create_table('cup_calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cup_id', sa.Integer(), nullable=False),
    sa.Column('tare_g', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('calibrated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('calibrated_by', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['calibrated_by'], ['users.id'], name=op.f('fk_cup_calibrations_calibrated_by_users')),
    sa.ForeignKeyConstraint(['cup_id'], ['cups.id'], name=op.f('fk_cup_calibrations_cup_id_cups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cup_calibrations'))
    )
    op.create_index('ix_cup_cal_cup_time', 'cup_calibrations', ['cup_id', 'calibrated_at'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_projects_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('name', name=op.f('uq_projects_name'))
    )
    op.create_index('ix_projects_active_created', 'projects', ['is_active', 'created_at'], unique=False)
    op.create_index('ix_projects_created_at_desc', 'projects', ['created_at'], unique=False)
    op.create_table('scales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('protocol_type', sa.String(length=32), nullable=False),
    sa.Column('baud_rate', sa.Integer(), nullable=False),
    sa.Column('data_bits', sa.SmallInteger(), nullable=False),
    sa.Column('parity', sa.String(length=8), nullable=False),
    sa.Column('stop_bits', sa.SmallInteger(), nullable=False),
    sa.Column('flow_control', sa.String(length=8), nullable=False),
    sa.Column('read_timeout_ms', sa.Integer(), nullable=False),
    sa.Column('decimal_places', sa.SmallInteger(), nullable=False),
    sa.Column('unit_default', sa.String(length=8), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_scales_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scales'))
    )
    op.create_table('verticals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_verticals_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verticals')),
    sa.UniqueConstraint('project_id', 'code', name='uq_vertical_project_code')
    )
    op.create_index('ix_verticals_proj_sort', 'verticals', ['project_id', 'sort_order'], unique=False)
    op.create_table('weighing_records',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_uid', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('vertical_id', sa.Integer(), nullable=False),
    sa.Column('tide_type', sa.String(length=8), nullable=True),
    sa.Column('sample_date', sa.Date(), nullable=False),
    sa.Column('water_depth_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('volume_ml', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_avg_concentration', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], name=op.f('fk_weighing_records_operator_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_weighing_records_project_id_projects')),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_weighing_records_vertical_id_verticals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weighing_records')),
    sa.UniqueConstraint('client_uid', name=op.f('uq_weighing_records_client_uid'))
    )
    op.create_index('ix_rec_created', 'weighing_records', ['created_at'], unique=False)
    op.create_index('ix_rec_points_gin', 'weighing_records', ['points'], unique=False, postgresql_using='gin', postgresql_ops={'points': 'jsonb_path_ops'})
    op.create_index('ix_rec_proj_vert_date', 'weighing_records', ['project_id', 'vertical_id', 'sample_date'], unique=False)
    # ### end Alembic commands ###

    # 表达式 GIN 索引：从 points 数组里抽 cup_number / cup_id 反查（spec §7.6）。
    # PG 不允许子查询直接进索引表达式，改为 IMMUTABLE 函数包装。
    op.execute(
        """
        CREATE OR REPLACE FUNCTION rec_points_cup_numbers(points jsonb)
        RETURNS text[]
        LANGUAGE sql
        IMMUTABLE
        STRICT
        PARALLEL SAFE
        AS $$
            SELECT array_agg(elem->>'cup_number') FROM jsonb_array_elements(points) AS elem
        $$
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION rec_points_cup_ids(points jsonb)
        RETURNS bigint[]
        LANGUAGE sql
        IMMUTABLE
        STRICT
        PARALLEL SAFE
        AS $$
            SELECT array_agg((elem->>'cup_id')::bigint) FROM jsonb_array_elements(points) AS elem
        $$
        """
    )
    op.execute(
        """
        CREATE INDEX ix_rec_points_cup_numbers ON weighing_records
        USING gin (rec_points_cup_numbers(points))
        """
    )
    op.execute(
        """
        CREATE INDEX ix_rec_points_cup_ids ON weighing_records
        USING gin (rec_points_cup_ids(points))
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # 先删手工加的表达式索引 + 辅助函数（autogen 不会镜像）
    op.execute("DROP INDEX IF EXISTS ix_rec_points_cup_ids")
    op.execute("DROP INDEX IF EXISTS ix_rec_points_cup_numbers")
    op.execute("DROP FUNCTION IF EXISTS rec_points_cup_ids(jsonb)")
    op.execute("DROP FUNCTION IF EXISTS rec_points_cup_numbers(jsonb)")
    # 不要 drop pg_trgm（其他表/未来迁移可能也用）
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rec_proj_vert_date', table_name='weighing_records')
    op.drop_index('ix_rec_points_gin', table_name='weighing_records', postgresql_using='gin', postgresql_ops={'points': 'jsonb_path_ops'})
    op.drop_index('ix_rec_created', table_name='weighing_records')
    op.drop_table('weighing_records')
    op.drop_index('ix_verticals_proj_sort', table_name='verticals')
    op.drop_table('verticals')
    op.drop_table('scales')
    op.drop_index('ix_projects_created_at_desc', table_name='projects')
    op.drop_index('ix_projects_active_created', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_cup_cal_cup_time', table_name='cup_calibrations')
    op.drop_table('cup_calibrations')
    op.drop_index('ix_cups_number_trgm', table_name='cups', postgresql_using='gin', postgresql_ops={'cup_number': 'gin_trgm_ops'})
    op.drop_table('cups')
    # ### end Alembic commands ###
